---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Develop:
    - ChatGPT:
        - abbr: CG
          href: https://chat.openai.com/
          icon: https://chat.openai.com/favicon.ico
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: https://github.githubassets.com/favicons/favicon-dark.svg
    - VSCode:
        - abbr: VS
          href: https://vscode.dev/
          icon: https://code.visualstudio.com/favicon.ico
    - Homepage Docs:
        - abbr: HP
          href: https://gethomepage.dev/latest/configs/
          icon: https://gethomepage.dev/latest/assets/light_squircle@2x.png
    - SSH:
        - abbr: SH
          href: ssh://ynng-dev-pc
          icon: https://fedoraproject.org/favicon.ico
    - Remote Desktop:
        - abbr: RD
          href: "ms-rd:"
          icon: https://ynng.ca/rdp.png

- Utilities:
    - Inside Tesla:
        - abbr: IT
          href: https://inside.tesla.com/
          icon: https://inside.tesla.com/favicon.ico
    - Google Calendar:
        - abbr: GC
          href: https://calendar.google.com/
          icon: https://calendar.google.com/googlecalendar/images/favicons_2020q4/calendar_31.ico
    - Google Maps:
        - abbr: GM
          href: https://www.google.com/maps
          icon: https://www.google.com/images/branding/product/ico/maps15_bnuw3a_32dp.ico
    - Quest:
        - abbr: UW
          href: https://quest.pecs.uwaterloo.ca/psp/SS/ACADEMIC/SA/?cmd=login&languageCd=ENG
          icon: https://uwaterloo.ca/favicon.ico
- Temptations:
    - Amazon:
        - abbr: AZ
          href: https://amazon.com/
          icon: https://www.amazon.com/favicon.ico
    - Taobao:
        - abbr: TB
          href: https://taobao.com/
          icon: https://www.taobao.com/favicon.ico
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-57x57.png
    - Twitter:
        - abbr: TW
          href: https://twitter.com/
          icon: https://abs.twimg.com/favicons/twitter.ico
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: https://www.youtube.com/s/desktop/d222600b/img/favicon_48x48.png
