---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Public:
    - Immich:
        href: https://immich.ynng.ca
        icon: https://immich.ynng.ca/favicon.ico
        description: Google Photo alternative
        server: ynng-dev-pc
        container: immich_server
        widget:
            type: immich
            url: http://localhost:12374
            key: REPLACEME
    - Jellyfin:
        href: https://jellyfin.ynng.ca
        icon: https://jellyfin.org/images/favicon.ico
        description: Watch totally legal movies, shows and anime
        server: ynng-dev-pc
        container: jellyfin
        widget:
            type: jellyfin
            url: http://localhost:8096
            key: REPLACEME
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
    - Plex:
        href: https://app.plex.tv/
        icon: https://plex.tv/favicon.ico
        siteMonitor: http://localhost:32400
        description: Worse proprietary jellyfin
        widget:
            type: plex
            url: http://localhost:32400
            key: REPLACEME
- Admin:
    - Portainer:
        href: http://ynng-dev-pc:9000
        server: ynng-dev-pc
        icon: https://portainer.io/favicon.ico
        description: Docker container management
        container: portainer
        widget:
            type: portainer
            env: 1
            url: http://localhost:9000
            key: REPLACEME
    - Caddy:
        icon: https://caddyserver.com/resources/images/favicon.png
        description: Reverse proxy server
        server: ynng-dev-pc
        container: caddy-caddy-1
        widget:
            type: caddy
            url: http://localhost:2019
    - Speedtest:
        href: http://ynng-dev-pc:61205
        icon: https://docs.speedtest-tracker.dev/~gitbook/icon?size=small&theme=light
        description: Speedtest tracker
        server: ynng-dev-pc
        container: speedtest-tracker
        widget:
            type: speedtest
            url: http://localhost:61205
