---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Apps:
    - Immich:
        href: https://immich.ynng.ca
        icon: https://immich.ynng.ca/favicon.ico
        description: Google Photo alternative
        server: ynng-dev-pc
        container: immich_server
        widget:
            type: immich
            url: http://localhost:12374
            key: <key>
    - Jellyfin:
        href: https://jellyfin.ynng.ca
        icon: https://jellyfin.org/images/favicon.ico
        description: Watch totally legal movies, shows and anime
        server: ynng-dev-pc
        container: jellyfin
        widget:
            type: jellyfin
            url: http://localhost:8096
            key: <key>
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
    - Jellyseerr:
        href: https://jellyseerr.ynng.ca
        icon: https://jellyseerr.ynng.ca/favicon.ico
        description: Download movies and shows
        server: ynng-dev-pc
        container: jellyseerr
        widget:
            type: jellyseerr
            url: http://localhost:5055
            key: <key>
- Media:
    # - Plex:
    #     href: https://app.plex.tv/
    #     icon: https://plex.tv/favicon.ico
    #     siteMonitor: http://localhost:32400
    #     description: Worse proprietary jellyfin
    #     widget:
    #         type: plex
    #         url: http://localhost:32400
    #         key: hTcUzHah-zCwe7WVpUzA
    - Sonarr:
        href: http://ynng-dev-pc:8989
        icon: https://sonarr.tv/img/logo.png
        description: TV show and anime management
        server: ynng-dev-pc
        container: sonarr
        widget:
            type: sonarr
            url: http://localhost:8989
            key: <key>
            enableQueue: true
    - Bazarr:
        href: http://ynng-dev-pc:6767
        icon: https://www.bazarr.media/assets/img/logo.png
        description: Subtitle management
        server: ynng-dev-pc
        container: bazarr
        widget:
            type: bazarr
            url: http://localhost:6767
            key: <key>
    - qBittorrent:
        href: http://ynng-dev-pc:51436
        icon: https://www.qbittorrent.org/favicon.ico
        description: Torrent client
        server: ynng-dev-pc
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://localhost:51436
            username: <key>
            password: <key>
    - Radarr:
        href: http://ynng-dev-pc:7878
        icon: https://radarr.video/img/logo.png
        description: Movie management
        server: ynng-dev-pc
        container: radarr
        widget:
            type: radarr
            url: http://localhost:7878
            key: <key>
            enableQueue: true
    - Jackett:
        href: http://ynng-dev-pc:9117
        icon: https://avatars.githubusercontent.com/u/15383019?s=48&v=4
        description: Torrent indexer
        server: ynng-dev-pc
        container: jackett
        widget:
            type: jackett
            url: http://localhost:9117
            password: <key>

- Admin:
    - Portainer:
        href: http://ynng-dev-pc:9000
        server: ynng-dev-pc
        icon: https://portainer.io/favicon.ico
        description: Docker container management
        container: portainer
        widget:
            type: portainer
            env: 1
            url: http://localhost:9000
            key: <key>

- Infalstructural:
    - Caddy:
        icon: https://caddyserver.com/resources/images/favicon.png
        description: Reverse proxy server
        server: ynng-dev-pc
        container: caddy-caddy-1
        widget:
            type: caddy
            url: http://localhost:2019
    - Speedtest:
        href: http://ynng-dev-pc:61205
        icon: https://docs.speedtest-tracker.dev/~gitbook/icon?size=small&theme=light
        description: Speedtest tracker
        server: ynng-dev-pc
        container: speedtest-tracker
        widget:
            type: speedtest
            url: http://localhost:61205
    - FlareSolverr:
        href: http://ynng-dev-pc:8191
        icon: https://avatars.githubusercontent.com/u/75936191?s=48&v=4
        description: Cloudflare bypass
        server: ynng-dev-pc
        container: flaresolverr
    - DDNS-Updater:
        href: http://ynng-dev-pc:7684/
        icon: https://raw.githubusercontent.com/qdm12/ddns-updater/master/readme/ddnsgopher.svg
        description: Dynamic DNS updater
        server: ynng-dev-pc
        container: ddns-updater
    - log:
        href: https://log.ynng.ca
        icon: https://goaccess.io/assets/ico/favicon.ico
        description: Web server log
        server: ynng-dev-pc
        container: goaccess-goaccess-1
